trigger: none

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Stage1
  displayName: Stage 1
  jobs:
  - job: Stage1_Job1
    displayName: Stage 1 Job 1
    steps:
      - bash: |
          echo SET FOO $FOO
          export FOO="'FooValue'"
          echo SET BAR with the value of FOO
          echo "##vso[task.setvariable variable=BAR;isOutput=true]$FOO"
        name: Stage1_Job1_Task1
        displayName: Task1 - Set FOO into BAR

  - job: Stage1Job2
    displayName: Stage 1 Job 2
    variables:
      BAZ_Stage1_Job2: $[ dependencies.Stage1_Job1.outputs['Stage1_Job1_Task1.BAR'] ]    
    dependsOn: Stage1_Job1    
    steps:
    - bash: |
        echo "BAZ in Job2 equals BAR with the value of FOO: $(BAZ_Stage1_Job2)"
      displayName: "Job2, BAZ = BAR From FOO"